### ISSUE TITLE
AEROSPIKE_SERVER_ID should not contain domain name

### ISSUE THREAD

**Issue by mbielecki-rtbh** [aerospike-community/aerospike-graphite#7]
On some hosts socket.gethostname() gives just host name on others it returns host name together with domain name, the AEROSPIKE_SERVER_ID should always be just the host name without the domain name, as the domain name (reversed) can optionally be passed as graphite_prefix.

**Comment by mbielecki-rtbh** [comment]
fixed by #9

**Comment by whyrg** [comment]
This particular solution only accounts for a simple host.domain.tld config, but what about multi-part tlds like .co.uk, .co.jp and sub-domains? 

To be able to handle all the differing scenarios, the plugin will just accept what the OS returns. In this case, the entire FQDN is returned by `hostname`, instead of properly split between `hostname` and `domainname`. Our graphite connector will not presume to know better than the OS and attempt to parse out a "correct" value.
